title: Brandon Li
email: librandon729@gmail.com
logo: /assets/img/headshot_circle.png
description: Hey! I'm a recent graduate from the University of Chicago who majored in Business Economics and minored in Computer Science.
show_downloads: true
theme: jekyll-theme-minimal
